/** Light, high-contrast Clerk UI on top of the dark neo-tech site shell. */
export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#ff6b5c",
    colorBackground: "#f6f8fc",
    colorText: "#0b0d14",
    colorTextSecondary: "#5a6278",
    colorTextOnPrimaryBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorNeutral: "#dce2ee",
    borderRadius: "14px",
    fontSize: "15px",
  },
  elements: {
    rootBox: "clerk-neo-root",
    card: "clerk-neo-card",
    socialButtonsBlockButton: "clerk-neo-oauth",
    formButtonPrimary: "clerk-neo-primary",
    footer: "clerk-neo-footer",
    formFieldLabel: "clerk-neo-label",
    formFieldInput: "clerk-neo-input",
    identityPreviewText: "clerk-neo-preview",
    formFieldSuccessText: "clerk-neo-hint",
    formFieldErrorText: "clerk-neo-error",
    formFieldHintText: "clerk-neo-hint",
    dividerLine: "clerk-neo-divider",
    dividerText: "clerk-neo-divider-text",
    footerAction: "clerk-neo-footer-action",
    footerActionLink: "clerk-neo-footer-link",
    logoBox: "clerk-neo-logo",
    headerTitle: "clerk-neo-header-title",
    headerSubtitle: "clerk-neo-header-subtitle",
  },
} as const;
